version: "3"
services:

  webserver:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
    - "80:80"

  frontend:
    build:
      context: ../../frontend
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    ports:
    - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ../../backend
    environment:
      ZEO_ADDRESS: zeo:8100
    ports:
      - "8080:8080"
    depends_on:
      - zeo

  zeo:
    image: plone/plone-zeo:latest
    volumes:
      - data:/var/lib/zeo/data
    ports:
      - "8100:8100"

volumes:
  data: {}
